openapi: 3.0.0
info:
  title: Example with multiple request and response types
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/test:
    post:
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  name:
                    $ref: '#/components/schemas/Text'
        '200':
          description: No content
components:
  schemas:
    Text:
      type: string
